### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by evan-stripe** [nelhage/crossme#4]
Haven't figured out why yet, but the Jul 5, 2016 NYTimes `.puz` file fails to parse with the following backtrace:

```
I20161204-15:36:07.657(-8)? Exception while invoking method 'uploadPuzzle' TypeError: Cannot read property '0' of undefined
I20161204-15:36:07.696(-8)?     at [object Object].Meteor.methods.uploadPuzzle (app/server/upload.js:36:26)
I20161204-15:36:07.697(-8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20161204-15:36:07.697(-8)?     at packages/ddp-server/livedata_server.js:711:19
I20161204-15:36:07.697(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161204-15:36:07.697(-8)?     at packages/ddp-server/livedata_server.js:709:40
I20161204-15:36:07.697(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20161204-15:36:07.697(-8)?     at packages/ddp-server/livedata_server.js:707:46
I20161204-15:36:07.698(-8)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20161204-15:36:07.698(-8)?     at packages/ddp-server/livedata_server.js:551:43
```

**Comment by evan-stripe** [comment]
Ah, never mind - this is my fault. That particular file for some reason doesn't have the GEXT section, so the `circled` attribute never gets populated.

**Comment by nelhage-stripe** [comment]
Do you have a patch? I can throw one together this evening or so if not.
